### ISSUE TITLE
ImportError: cannot import name 'latexmk' from 'plumbum.cmd

### ISSUE THREAD

**Issue by DaDaYaer** [Lancelot39/Causal-Copilot#24]
>python main.py --data_file "E:/00Dropbox/UFL Dropbox/Xueyan Gao/Gates Project_Course Sequencing in FL and WV/Wei Analysis/Xueyan's work/6_MathPathAnalysis_20241106/3_Causal Copilot_241119/MathPath_Dataset/df_Persis_First1term_sub.csv" --apikey My openai apikey --initial_query “YES. Find causal relationships between student’s enrolment status in next term and the course taken in one term.”
Traceback (most recent call last):
  File "E:\00Dropbox\UFL Dropbox\Xueyan Gao\Gates Project_Course Sequencing in FL and WV\Wei Analysis\Xueyan's work\6_MathPathAnalysis_20241106\3_Causal Copilot_241119\Causal-Copilot-main\main.py", line 11, in <module>
    from postprocess.report_generation import Report_generation
  File "E:\00Dropbox\UFL Dropbox\Xueyan Gao\Gates Project_Course Sequencing in FL and WV\Wei Analysis\Xueyan's work\6_MathPathAnalysis_20241106\3_Causal Copilot_241119\Causal-Copilot-main\postprocess\report_generation.py", line 5, in <module>
    from plumbum.cmd import latexmk
ImportError: cannot import name 'latexmk' from 'plumbum.cmd' (D:\anaconda\envs\causal\lib\site-packages\plumbum\cmd.py)

**Comment by WenyiWU0111** [comment]
To solve this issue, please try to run the following commands in the terminal:
--------------------------
tex dependency (mac os):
rm -rf ~/Library/TinyTeX
wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
export PATH="$PATH:$HOME/Library/TinyTeX/bin/universal-darwin" 
source ~/.zshrc

tlmgr update --self
tlmgr install fancyhdr caption subcaption nicefrac microtype lipsum graphics natbib doi
--------------------------
tex dependency (Linux):
rm -rf ~/.TinyTeX
wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
export PATH="$PATH:$HOME/.TinyTeX/bin/x86_64-linux"
source ~/.bashrc

tlmgr update --self
tlmgr install fancyhdr caption subcaption nicefrac microtype lipsum graphics natbib doi
--------------------------
You can use this command `which pdflatex` to check whether you have installed xelatex/pdflatex

**Comment by fwu6492** [comment]
Hi, I'm running into an issue while trying to run the command "tlmgr update --self" 

felixwu@Felixs-MacBook-Air ~ % export PATH="$PATH:$HOME/Library/TinyTeX/bin/universal-darwin"
felixwu@Felixs-MacBook-Air ~ % source ~/.zprofile                                            
felixwu@Felixs-MacBook-Air ~ % cd Causal-Copilot 
felixwu@Felixs-MacBook-Air Causal-Copilot % tlmgr update --self
tlmgr: package repository https://ctan.mirrors.hoobly.com/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr: no self-updates for tlmgr available
